use crate::api::{
    Activity, AnchorData, AuditAcknowledged, AuditRead, Book, BookChapter, CaptureSource,
    Dashboard, DayMinutes, Domain, Note, Progress, RateResult, Task, Timer, TimerCandidate,
    TimerSettings, TimerStopped, Today, Topic, Week,
};
use crate::app::screens::review::Rating;
use crate::app::screens::ScreenKind;
use crate::queue::{Intent, ReplayReport};
use crate::ui::notify::Level;

#[derive(Debug)]
pub enum Action {
    Quit,
    Goto(ScreenKind),
    SetUser(String),
    FetchMe,
    Notify {
        level: Level,
        text: String,
    },
    DismissNotification,

    // Auth
    Login,
    LoginSucceeded,
    LoginFailed(String),
    LoginServerError(String),
    SessionExpired,

    // Home
    TodayLoaded(Box<Today>),
    HomeLoadFailed(String),
    RefreshHome,
    HomeInboxLoaded {
        pending: usize,
        expiring: bool,
    },

    // Books
    BooksLoaded(Vec<Book>),
    BooksLoadFailed(String),
    BooksFilter(BooksFilter),
    BooksSearchInput(char),
    BooksSearchBackspace,
    BooksSearchSubmit,
    BooksSearchCancel,
    BooksMove(i32),
    BooksMatchStep(i32),
    BooksJumpStart,
    BooksJumpEnd,
    BooksOpen,
    BooksPickerOpen,
    BooksPickerKey(crossterm::event::KeyEvent),

    // Book detail
    BookDetailLoaded {
        book: Box<Book>,
        chapters: Vec<BookChapter>,
    },
    BookDetailLoadFailed(String),
    ChapterMove(i32),
    ToggleChapterDone,
    BeginEditPage,
    EditPageInput(char),
    EditPageBackspace,
    SubmitPage,
    CancelEdit,
    // Status picker modal
    BookStatusPicker,
    BookStatusMove(i32),
    BookStatusSelect(crate::api::BookStatus),
    BookStatusConfirm,
    BookStatusCancel,
    BookUpdated(Box<Book>),

    // Activity new
    ActivityFieldNext,
    ActivityFieldPrev,
    ActivityEnterInsert,
    ActivityLeaveInsert,
    ActivityKey(crossterm::event::KeyEvent),
    ActivitySubmit,
    ActivityCreated,
    ActivityFailed {
        errors: Vec<crate::api::FieldError>,
        detail: String,
    },

    // Progress
    ProgressLoaded(Box<Progress>),
    ProgressLoadFailed(String),
    ProgressWeekStep(i32),
    ProgressWeekReset,
    RefreshProgress,
    ProgressFoldCycle,
    ProgressSelectMove(i32),
    ProgressAdjustBegin,
    ProgressAdjustInput(char),
    ProgressAdjustBackspace,
    ProgressAdjustSubmit,
    ProgressAdjustCancel,
    ProgressRetire,
    // Declare a new target
    ProgressDeclareBegin,
    ProgressDeclareReady(Vec<Domain>),
    ProgressDeclareKey(crossterm::event::KeyEvent),
    ProgressDeclareQueued(String),

    // Timer: the header cell (app-owned snapshot) and the Timer screen
    RefreshTimer,
    TimerLoaded(Box<Timer>),
    TimerStale(Box<Timer>),
    TimerProvisional(Box<Timer>),
    ReplayProgress {
        word: String,
    },
    ReplayFinished(ReplayReport),
    TimerDivergedLoaded(Option<Box<Intent>>),
    TimerReconcileBoth,
    TimerReconcileEdit,
    TimerReconcileEditApply {
        intent_id: u64,
        buffer: String,
    },
    TimerReconcileDrop,
    TimerReconcileSkip,
    QueueIntentEdit {
        intent_id: u64,
        seed: String,
    },
    TimerCleared,
    TimerReload,
    TimerSave,
    TimerPauseResume,
    TimerStop,
    TimerToggleRail,
    TimerModeSwitch,
    TimerSkipInterval,
    TimerBreak,
    TimerTodayLoaded(u32),
    TimerWeekLoaded(Vec<DayMinutes>),
    TimerStopped(Box<TimerStopped>),
    TimerDismissStopped,
    TimerDiscard,
    TimerBindBegin,
    TimerBindCancel,
    TimerPickerToggleMode,
    TimerUndo,
    TimerUndone,

    // Timer settings
    SettingsLoaded(Box<TimerSettings>),
    SettingsLoadFailed(String),
    SettingsReload,

    // Week board
    WeekLoaded(Box<Week>),
    WeekLoadFailed(String),
    WeekStep(i32),
    WeekReset,
    RefreshWeek,
    WeekSelectMove(i32),
    // Plan writes from the board
    WeekAddBegin,
    WeekAdjustBegin,
    WeekInputChar(char),
    WeekInputBackspace,
    WeekInputSubmit,
    WeekInputCancel,
    WeekDrop,
    WeekStartTimer,
    WeekPlanQueued(String),
    WeekReflect,
    WeekReflectEdit {
        iso_week: String,
        seed: String,
    },
    WeekReflectSave {
        iso_week: String,
        body: String,
    },
    WeekReflectAbort,
    WeekReflectQueued(String),

    // Segment audit
    AuditLoaded(Box<AuditRead>),
    AuditLoadFailed(String),
    AuditReload,
    AuditMove(i32),
    AuditAcknowledge,
    AuditAcknowledged(Box<AuditAcknowledged>),
    AuditTrim,
    AuditDelete,
    AuditFix,
    TimerBindInput(char),
    TimerBindBackspace,
    TimerBindMove(i32),
    TimerBindSubmit,
    TimerCandidatesLoaded(Vec<TimerCandidate>),

    // Activities
    ActivitiesLoaded {
        items: Vec<crate::queue::FoldedActivity>,
        page: u32,
        per_page: u32,
        total: u32,
    },
    ActivitiesLoadFailed(String),
    ActivitiesMove(i32),
    ActivitiesMatchStep(i32),
    ActivitiesJumpStart,
    ActivitiesJumpEnd,
    ActivitiesPageNext,
    ActivitiesPagePrev,
    ActivitiesCycleFilter,
    ActivitiesSearchInput(char),
    ActivitiesSearchBackspace,
    ActivitiesSearchSubmit,
    ActivitiesSearchCancel,
    ActivitiesOpenDetail,
    ActivitiesDetailLoaded(Box<Activity>),
    ActivitiesCloseDetail,
    ActivitiesComplete,
    ActivitiesArchive,
    ActivitiesDuplicate,
    ActivitiesStartTimer,
    RefreshActivities,

    // Notes
    NotesLoaded(Vec<Note>),
    NotesLoadFailed(String),
    NotesMove(i32),
    NotesMatchStep(i32),
    NotesJumpStart,
    NotesJumpEnd,
    NotesSearchInput(char),
    NotesSearchBackspace,
    NotesSearchSubmit,
    NotesSearchCancel,
    NotesOpenDetail,
    NotesDetailLoaded(Box<Note>),
    NotesCloseDetail,
    NotesToggleArchived,
    NotesArchiveSelected,
    NotesEditSelected,
    NotesUnlinkSelected,
    NotesDeleteArm,
    NotesDeleteConfirm,
    NotesDeleteDisarm,
    RefreshNotes,

    // Review: the dashboard, the rating sitting, and browse-all
    ReviewDashboardLoaded(Box<Dashboard>),
    ReviewLoadFailed(String),
    RefreshReview,
    ReviewOpenDashboard,
    ReviewOpenBrowse,
    ReviewStartSitting,
    ReviewExitSitting,
    ReviewRate(Rating),
    ReviewRated(Box<RateResult>),
    ReviewRateFailed,
    ReviewBrowseLoaded {
        items: Vec<Topic>,
        page: u32,
        per_page: u32,
        total: u32,
    },
    ReviewBrowseMove(i32),
    ReviewBrowseMatchStep(i32),
    ReviewBrowseJumpStart,
    ReviewBrowseJumpEnd,
    ReviewBrowsePageNext,
    ReviewBrowsePagePrev,
    ReviewBrowseCycleSort,
    ReviewBrowseSearchInput(char),
    ReviewBrowseSearchBackspace,
    ReviewBrowseSearchSubmit,
    ReviewBrowseSearchCancel,
    ReviewBrowseOpenDetail,
    ReviewBrowseDetailLoaded(Box<Topic>),
    ReviewBrowseCloseDetail,

    // Inbox
    InboxLoaded(Vec<Task>),
    InboxLoadFailed(String),
    RefreshInbox,
    InboxMove(i32),
    InboxOpen,
    InboxCloseDetail,
    InboxDraftStep(i32),
    InboxAccept,
    InboxAck,
    InboxRejectBegin,
    InboxRejectInput(char),
    InboxRejectBackspace,
    InboxRejectSubmit,
    InboxRejectCancel,
    InboxActionFailed,

    // Connect
    ConnectLoaded(Vec<CaptureSource>),
    ConnectLoadFailed(String),
    RefreshConnect,
    ConnectMove(i32),
    ConnectBegin,
    ConnectDisconnectBegin,
    ConnectSync,
    ConnectPromptSubmit,
    ConnectPromptCancel,
    ConnectFeedInput(char),
    ConnectFeedBackspace,
    ConnectActionFailed,

    // Queue inspector
    QueueLoaded(Vec<Intent>),
    QueueLoadFailed(String),
    QueueRefresh,
    QueueSelectMove(i32),
    QueueRetry,
    QueueDropSelected,
    QueueOpenReconcile,

    // Quick-capture overlay
    CaptureOpen,
    CaptureOpenText(String),
    CaptureOpenEdit(Box<Note>),
    CaptureClose,
    CaptureSaved,
    CaptureKey(crossterm::event::KeyEvent),
    CaptureEditExternal,
    CaptureSave,
    CaptureSaveFailed,
    CaptureCancel,
    CaptureFieldNext,
    CaptureFieldPrev,
    CaptureBookInput(char),
    CaptureBookBackspace,
    CaptureBookMove(i32),
    CaptureBookPickerSubmit,
    CaptureBookPickerClose,
    CaptureBookResults(Vec<Book>),
    CaptureAnchorPickerOpen,
    CaptureAnchorPickerClose,
    CaptureAnchorPickerSubmit,
    CaptureAnchorMove(i32),
    CaptureAnchorInput(char),
    CaptureAnchorBackspace,
    CaptureAnchorDataLoaded(Box<AnchorData>),
    CaptureAnchorDataFailed(String),

    // Command mode. The buffer is mutated in the event layer; these are signals.
    CommandBegin,
    CommandInput,
    CommandBackspace,
    CommandSubmit,
    CommandCancel,
}

#[derive(Debug, Clone, Copy)]
pub enum BooksFilter {
    All,
    Reading,
    Completed,
}
